### ISSUE TITLE
Prebuilt Docker Image

### ISSUE THREAD

**Issue by andrasbacsai** [basecamp/fizzy#1801]
Do you plan to provide a prebuilt image for this?

**Comment by d34ndev** [comment]
Was just wondering this myself!

**Comment by ChandeepKhosa** [comment]
I suspect not as they mention deploying with Kamal, which seems to do a better/simpler job instead of docker https://github.com/basecamp/fizzy?tab=readme-ov-file#deployment

**Comment by d34ndev** [comment]
Looks like that's been added with #1803

**Comment by monorkin** [comment]
Hi all 👋
I just added automated Docker image builds in https://github.com/basecamp/fizzy/pull/1803
You can find containers for the main branch and future tagged releases [here](https://github.com/basecamp/fizzy/pkgs/container/fizzy)
_(Just note that we create a tagged release each time we deploy with the SHA of the commit)_

**Comment by d34ndev** [comment]
> _(Just note that we create a tagged release each time we deploy with the SHA of the commit)_

Thanks! I wonder if it might be best to move that to building on release instead of on every push?

**Comment by andrasbacsai** [comment]
> Hi all 👋 I just added automated Docker image builds in [#1803](https://github.com/basecamp/fizzy/pull/1803) You can find containers for the main branch and future tagged releases [here](https://github.com/basecamp/fizzy/pkgs/container/fizzy) _(Just note that we create a tagged release each time we deploy with the SHA of the commit)_

Thanks for the quick action. Btw, do you plan to add arm based images as well? :)

**Comment by monorkin** [comment]
@andrasbacsai I'll give it a try tomorrow. I added them initially but some gems wouldn't compile so I opted to drop ARM support for now. If you have time to take a look into this I'd appreciate the help 🙏

**Comment by monorkin** [comment]
@deanpcmad we build on every merge to main and on every release, but we have a hook that creates a release every time we deploy something to production.
Having a build on every commit in main means that you can run any feature as soon as its merged, while the releases allow you to run the same code that we run in production.

**Comment by Aerics84** [comment]
Thanks for the containers.
But where can i find any informations about mounting points for the volumens?
Or do i need a container with a database?
Any enviroment variables i need?

**Comment by kevinmcconnell** [comment]
@Aerics84 we're sorting out some simpler set for this at the moment, in terms of environment variables and related configuration. We'll document it all in the README as it takes shape. Stay tuned! :)

**Comment by skyfallwastaken** [comment]
I think ARM seems to work now - I just set Fizzy up in dev mode on Ubuntu 25.10 arm64 (via OrbStack) and everything seems to work perfectly!

**Comment by monorkin** [comment]
@SkyfallWasTaken Did you dry to build a production image? That's what was failing when I made the decision to ditch ARM for the moment. If I remember right, some gems failed to install due to a compilation error. It might be that the image is missing some dependency.

**Comment by skyfallwastaken** [comment]
If I understand it correctly, this is the command the action uses to build for production:

```
/usr/bin/docker buildx build --file Dockerfile --label org.opencontainers.image.version=sha-fbdb345-arm64 --platform linux/arm64 .
```
(I know there's a shorter way to do it but I want to match the action decently closely)

The build works fine with no errors, so I think it should work now (the action was previously using 24.04 for ARM which could be related?)

**Comment by dvogt23** [comment]
Would like to try it on my raspi, but arm still not available :// any progress here?

**Comment by renannprado** [comment]
@dvogt23 it could be #2305 helps you. I didn't try from a raspberry pi, but maybe it works.
